name: Deploy Multidocker
on:
    push:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/react-test -f ./client/Dockerfile.dev ./client
            - run: docker run -e CI=true ${{ secrets.DOCKERHUB_USERNAME }}/react-test npm test
    
    login:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - 
                name: Login to dockerhub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    build:
        needs: login
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/multi-client ./client
            - run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/multi-nginx ./nginx
            - run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/multi-server ./server
            - run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/multi-worker ./worker
       
            - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/multi-client
            - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/multi-nginx
            - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/multi-server
            - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/multi-worker